// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlrbcgshufcjmvmkehmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscmJjZ3NodWZjam12bWtlaG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODQwNzUsImV4cCI6MjA2Mzg2MDA3NX0.G2DzIvZGFUdn8k672gS6v9mzRo34VKM7r1eyODKY5QQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);